name: Deploy to Web Host

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]  # Only when PR is merged
  workflow_dispatch:    # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only deploy on push to main, merged PRs, or manual trigger
    if: github.event_name == 'workflow_dispatch' || 
        github.ref == 'refs/heads/main' ||
        (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore -c Release
    
    - name: Publish
      run: dotnet publish ./PatinaBlazor/PatinaBlazor/PatinaBlazor.csproj -c Release -o ./publish --no-build --no-self-contained -p:PublishSingleFile=false -p:PublishTrimmed=false

    - name: Clean up debug files and localization
      run: |
        # Remove debugging and development files that shouldn't be deployed
        rm -rf ./publish/BlazorDebugProxy/
        rm -f ./publish/*.pdb
        rm -f ./publish/appsettings.Development.json
        find ./publish -name "*.pdb" -delete
        find ./publish -name "*Debug*" -delete

        # Remove localization folders that may cause FTP issues
        rm -rf ./publish/cs/
        rm -rf ./publish/de/
        rm -rf ./publish/es/
        rm -rf ./publish/fr/
        rm -rf ./publish/it/
        rm -rf ./publish/ja/
        rm -rf ./publish/ko/
        rm -rf ./publish/pl/
        rm -rf ./publish/pt/
        rm -rf ./publish/ru/
        rm -rf ./publish/zh/
        rm -rf ./publish/zh-Hans/
        rm -rf ./publish/zh-Hant/

        # List remaining files for debugging
        echo "Files being deployed:"
        find ./publish -type f | head -20
      shell: bash
    
    - name: Replace database password
      run: |
        sed -i 's/\*\*\*\*PROD_DB_PASSWORD\*\*\*\*/'"${{ secrets.PROD_DB_PASSWORD }}"'/g' ./publish/appsettings.Production.json
      shell: bash
    
    - name: Add web.config for IIS
      run: |
        if [ ! -f ./publish/web.config ]; then
          cat > ./publish/web.config << 'EOF'
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <location path="." inheritInChildApplications="false">
            <system.webServer>
              <handlers>
                <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModuleV2" resourceType="Unspecified" />
              </handlers>
              <aspNetCore processPath="dotnet" arguments=".\PatinaBlazor.dll" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" hostingModel="inprocess" />
            </system.webServer>
          </location>
        </configuration>
        EOF
        fi
      shell: bash
    
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/
        server-dir: /
        exclude: |
          **/*.pdb
          **/BlazorDebugProxy/**
          **/appsettings.Development.json
          **/*Debug*
          **/cs/**
          **/de/**
          **/es/**
          **/fr/**
          **/it/**
          **/ja/**
          **/ko/**
          **/pl/**
          **/pt/**
          **/ru/**
          **/zh/**
          **/zh-Hans/**
          **/zh-Hant/**
